# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atoulous <atoulous@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/11/01 16:51:18 by atoulous          #+#    #+#              #
#    Updated: 2015/11/01 22:05:01 by atoulous         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Colle-2

SRC = *.c

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean:
	/bin/sh/rm -f *.o

fclean: clean
	/bin/sh/rm -f $(NAME)

re: fclean all
